#!/bin/bash -xv

t="/tmp/automake.$$"

while ps $$ > /dev/null ; do 
    sleep 1
    [ -e "$t" ] || continue
    rm -f "$t"
    make
done &

inotifywait -rm -e close_write ./    |
while read line ; do
    touch "$t"
done
